# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ScratchCardSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScratchCardSample

    pod 'AAScratchView'

end
